name: mods_guns
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  pa_core_flutter:
#    path: D:\Projects\PACoreFlutter
  pa_core_flutter:
    git:
      url: https://github.com/pamobilevn/PACoreFlutter.git
      ref: getx

  cupertino_icons: ^1.0.2
  get: ^3.26.0
  google_mobile_ads: ^0.11.0+2
  http: ^0.13.0
  flutter_inapp_purchase: ^4.0.2
  get_storage: ^2.0.1
  flutter_rating_bar: ^3.2.0+1
  cached_network_image: ^2.5.1
  pull_to_refresh: ^1.6.3
  path_provider: ^1.6.28
  share: ^2.0.1
  animated_text_kit: ^3.1.2
  gallery_saver: ^2.0.3
  launch_review: ^2.0.0
  package_info: ^0.4.3+4
#  firebase_remote_config: ^0.6.0
#  firebase_core: ^0.7.0
  firebase_core: ^0.6.0
  firebase_remote_config: ^0.5.0
  dio: ^3.0.10
  sn_progress_dialog: ^0.0.5
  archive: ^2.0.13
  flutter_archive: ^2.0.2
  device_info: ^1.0.0
  open_file: ^3.0.3
  flutter_widget_from_html: ^0.5.2+1
  url_launcher: ^5.7.10
  dio_http_cache: ^0.2.11
  flutter_svg: ^0.19.3
  shared_preferences: ^2.0.6
  app_tracking_transparency: ^1.0.1+1
  connectivity_plus: ^0.8.1
  fluttertoast: ^7.1.8

dependency_overrides:
  get_storage: ^1.4.0
  cached_network_image: ^2.3.1
  http: ^0.12.0+2
  gallery_saver:
    git:
      url: https://github.com/pamobilevn/gallery_saver.git
      ref: master
  share: ^0.6.5+4
  path: ^1.7.0
  open_file: ^3.0.3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/tutorial_image/android/
    - assets/images/tutorial_image/mods/
    - assets/images/icons_about/
    - assets/mcpe/projectile/
    - assets/mcpe/projectile/arrows/icons/
    - assets/mcpe/projectile/arrows/skins/
    - assets/mcpe/projectile/trident/icons/
    - assets/mcpe/projectile/trident/skins/
    - assets/mcpe/projectile/file/
    - assets/mcpe/projectile/icons/
    - assets/mcpe/projectile/shulker/
    - assets/mcpe/projectile/shulker/skins/
    - assets/mcpe/projectile/shulker/icons/
    - assets/mcpe/projectile/skins/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
